### ISSUE TITLE
Breaks when branch includes "/"

### ISSUE THREAD

**Issue by kevinschaul** [kevinschaul/open-in-github#5]
e.g. on branch `pub/graphic-config`, opens incorrect URL.

Incorrect: https://github.com/XX/XX/tree/pub/
Correct: https://github.com/XX/XX/tree/pub/graphic-config

**Comment by adjohnson916** [comment]
+1 Affects the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) workflow, which uses `/` characters in its branches.
